const actionTypes = {
  LOAD_SEARCH: 'LOAD_SEARCH',
  LOAD_SEARCH_ERROR: 'LOAD_SEARCH_ERROR',
  LOAD_MOVIE_DETAIL: 'LOAD_MOVIE_DETAIL',
  LOAD_MOVIE_DETAIL_ERROR: 'LOAD_MOVIE_DETAIL_ERROR',

  LOAD_POPULAR_MOVIES: 'LOAD_POPULAR_MOVIES',
  LOAD_POPULAR_MOVIES_ERROR: 'LOAD_POPULAR_MOVIES_ERROR',
};

export default actionTypes;
